# Site settings
title: Sebastian Carroll
email: sebastianjamescarroll@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software Engineer
  Continuous Improvement Enthusiast
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sebastiancarroll.github.io" # the base hostname & protocol for your site
twitter_username: sebjcarroll
github_username:  sebastiancarroll

# Build settings
markdown: kramdown
